version: '3.8'

services:
  xml-api:
    image: seu-registro/xml-downloader-api:1.0  # Substitua pela sua imagem
    networks:
      - traefik-public
    environment:
      - PYTHONPATH=/app
    deploy:
      replicas: 1  # Pode ser facilmente escalado: docker service scale stack_xml-api=3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        order: start-first
      # Uncomment to constrain deployment to specific node types
      # placement:
      #   constraints:
      #     - node.role == worker
      #     - node.labels.environment == production
      labels:
        # Habilitar Traefik para este serviço
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        
        # Configuração do Router HTTP (redirecionamento para HTTPS)
        - traefik.http.routers.xml-api.rule=Host(`api-xml.seu-dominio.com`)
        - traefik.http.routers.xml-api.entrypoints=web
        - traefik.http.routers.xml-api.middlewares=xml-api-redirect
        
        # Middleware para redirecionamento HTTPS
        - traefik.http.middlewares.xml-api-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.xml-api-redirect.redirectscheme.permanent=true
        
        # Configuração do Router HTTPS (principal)
        - traefik.http.routers.xml-api-secure.rule=Host(`api-xml.seu-dominio.com`)
        - traefik.http.routers.xml-api-secure.entrypoints=websecure
        - traefik.http.routers.xml-api-secure.tls=true
        - traefik.http.routers.xml-api-secure.tls.certresolver=letsencryptresolver
        
        # Configuração do Service (porta interna da aplicação)
        - traefik.http.services.xml-api.loadbalancer.server.port=8000
        
        # Health check personalizado (opcional)
        - traefik.http.services.xml-api.loadbalancer.healthcheck.path=/health
        - traefik.http.services.xml-api.loadbalancer.healthcheck.interval=30s
        - traefik.http.services.xml-api.loadbalancer.healthcheck.timeout=10s

networks:
  traefik-public:
    external: true